server:
    port: 9090
    

spring:
    cloud:
        gateway:
            routes:
                - id : CSI-PLATFORM-AUTH
                  uri: lb://CSI-PLATFORM-AUTH
                  predicates:
                      - Path=/csi-platform-auth/api/v1/**
                      - Method=GET,POST,PUT,DELETE
                  filters:
                      - name: CircuitBreaker
                        args: 
                            name: CSI-PLATFORM-AUTH
                            fallbackuri: /fallback/auth
                      - name: AuthenticationFilter

                - id : CSI-PLATFORM-SERVICE
                  uri: lb://CSI-PLATFORM-SERVICE
                  predicates:
                      - Path=/csi-platform-service/api/v1/**
                      - Method=GET,POST,PUT,DELETE
                  filters:
                      - name: CircuitBreaker
                        args: 
                            name: CSI-ACCOUNT-SERVICE
                            fallbackuri: /fallback/platform
                      - name: AuthenticationFilter

                - id : CSI-ACCOUNT-SERVICE
                  uri: lb://CSI-ACCOUNT-SERVICE
                  predicates:
                      - Path=/csi-account-service/api/v1/**
                      - Method=GET,POST,PUT,DELETE
                  filters:
                      - name: CircuitBreaker
                        args: 
                            name: CSI-ACCOUNT-SERVICE
                            fallbackuri: /fallback/account
                      - name: AuthenticationFilter

                - id : CSI-USER-SERVICE
                  uri: lb://CSI-USER-SERVICE
                  predicates:
                      - Path=/csi-user-service/api/v1/**
                      - Method=GET,POST,PUT,DELETE
                  filters:
                      - name: CircuitBreaker
                        args: 
                            name: CSI-USER-SERVICE
                            fallbackuri: /fallback/user
                      - name: AuthenticationFilter

app:
    jwt:
        secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP
